version: '3.7'

services:

  db:
    container_name: db
    image: postgres:13.0
    environment:
      POSTGRES_USER: $POSTGRES_USER
      POSTGRES_PASSWORD: $POSTGRES_PASSWORD
      POSTGRES_DB: $POSTGRES_DB
    networks:
      - spobmish_backend
    restart: always
    volumes:
      - ./postgres:/var/lib/postgresql/data

  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4:4.26
    environment:
      PGADMIN_DEFAULT_EMAIL: $PGADMIN_DEFAULT_EMAIL
      PGADMIN_DEFAULT_PASSWORD: $PGADMIN_DEFAULT_PASSWORD
      PGADMIN_LISTEN_PORT: $PGADMIN_PORT
      PGADMIN_ENABLE_TLS: "True"
    volumes:
      - ./$SSL_DIR$SSL_CERT:/certs/server.cert:ro
      - ./$SSL_DIR$SSL_PRIV:/certs/server.key:ro
#      - ./pgadmin/tmp/servers.json:/pgadmin4/servers.json
#      - ./pgadmin/private/var/lib/pgadmin:/var/lib/pgadmin
    ports:
      - $HOST_PGADMIN_PORT:$PGADMIN_PORT
    networks:
      - spobmish_backend
    restart: always
    depends_on:
      - db

  tgbot:
    container_name: tgbot
    build:
      context: ./$APP_BASE_DIR
      args:
        APP_BASE_DIR: $APP_BASE_DIR
    command: python app.py
    volumes:
      - ./$SSL_DIR$SSL_CERT:/$APP_BASE_DIR/$SSL_DIR$SSL_CERT:ro
      - ./$SSL_DIR$SSL_PRIV:/$APP_BASE_DIR/$SSL_DIR$SSL_PRIV:ro
    env_file:
      - .env
    ports:
      - $WEBHOOK_PORT:$WEBAPP_PORT
    networks:
      - spobmish_backend
    restart: always
    depends_on:
      - db

networks:
  spobmish_backend:
